language: java

jdk:
 - oraclejdk7
 - openjdk7
 - oraclejdk8

matrix:
 allow_failures:
   - openjdk7
   - oraclejdk7

notifications:
  email: false

install:
 - redis-server > /dev/null 2>&1 &
 - git submodule init
 - git submodule update --depth 1

cache:
 apt: true
 directories:
  - $HOME/.cache/pip
  - $HOME/.gradle/caches
  - $HOME/gradle
  - $HOME/qabel-core/.gradle/caches
  - $HOME/qabel-core/gradle
  - $HOME/build/qabel/qabel-drop/lib

sudo: false

addons:
 apt:
  packages:
   - python3
   - python3-pip
   - nodejs
   - python3-virtualenv

script:
 - travis_wait bash build.sh
